target "suixinAPP" do
pod 'MJRefresh', '~> 3.1.9'
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'FDFullscreenPopGesture', '~> 1.1'

pod 'MOBFoundation_IDFA'

pod 'SMSSDK'
end
